export const planList = [
    {
        supplier: 'OVO Business Energy',
        name: 'Super Saver May 2021 B2',
        annual_cost: 878.47,
        monthly_direct_debit: 73.21,
        green_plan: '100% renewable electricity - generated by OVO wind farms with zero CO2 emissions',
        description: 'By signing up to this tariff, you agree to have a smart meter installed by OVO within 3 months of switching, unless you already have one. You may stay on this tariff if they are unable to fit one for reasons outside of your control.'
    },
    {
        supplier: 'OVO Business Energy',
        name: 'OVO 2 Year Fix v2',
        annual_cost: 892.96,
        monthly_direct_debit: 74.41,
        green_plan: '100% renewable electricity',
        description: 'OVO Airtricity’s standard gas tariff with 10% MoneyBack on your total.'
    },
    {
        supplier: 'OVO Business Energy',
        name: 'OVO 1 Year Fix',
        annual_cost: 861.27,
        monthly_direct_debit: 71.77,
        green_plan: '100% renewable electricity - generated by ScottishPowers wind farms with zero CO2 emissions',
        description: 'By switching to OVO Energy, you will be offered an exclusive 3% saving on fuel at OVO service stations through the OVO Go+ rewards programme'
    },
];